services:
    pictorial.subscriber.entity_life_cycle:
        class: Mz\PictorialBundle\EventListener\EntityLifeCycleSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            container: "@service_container"


    packageVisits.validator:
            class: Mz\PictorialBundle\Validator\Constraints\PackageVisitsValidator
            arguments:
                em: "@doctrine.orm.entity_manager"
            tags:
                - { name: validator.constraint_validator, alias: packageVisits.validator }